CREATE TABLE IF NOT EXISTS USERS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  first_name TEXT ,
  last_name TEXT,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  age INTEGER,
  phone TEXT UNIQUE ,
  gender TEXT,
  education TEXT,
  image_file TEXT DEFAULT 'default.jpg' NOT NULL,
  experience TEXT
);

CREATE TABLE IF NOT EXISTS USER_SKILLS  (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  skill_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  level_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS LEVEL (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  level_name TEXT UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS SAVED_JOBS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  job_id INTEGER NOT NULL
);

