CREATE TABLE IF NOT EXISTS USERS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  first_name TEXT ,
  last_name TEXT,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  age INTEGER,
  phone TEXT UNIQUE ,
  gender TEXT,
  education TEXT,
  image_file TEXT DEFAULT 'default.jpg' NOT NULL,
  experience TEXT
);

CREATE TABLE IF NOT EXISTS USER_SKILLS  (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  skill_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  level_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS LEVEL (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  level_name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS JOBS_SKILLS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  job_id INTEGER NOT NULL,
  skill_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS SKILLS  (
  id TEXT PRIMARY KEY ,
  title TEXT   NOT NULL
);

CREATE TABLE IF NOT EXISTS JOBS (
  id INTEGER PRIMARY KEY ,
  company TEXT NOT NULL,
  img TEXT NOT NULL,
  title TEXT NOT NULL,
  deadline TEXT NOT NULL,
  category TEXT NOT NULL,
  job_type TEXT,
  job_desc TEXT,
  job_resp TEXT,
  req_qual TEXT,
  req_cond_level TEXT,
  salary TEXT,
  add_info TEXT

);

CREATE TABLE IF NOT EXISTS SAVED_JOBS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  job_id INTEGER NOT NULL
);

